<?php
echo '<?xml version="1.0" encoding="UTF-8"?>
<messages>
	<message>
		<text>текст1</text>
		<sender>имя1</sender>
		<date>дата1</date> 
	</message>
	<message>
		<text>текст2</text>
		<sender>имя2</sender>
		<date>дата2</date> 
	</message>
	<message>
		<text>текст3</text>
		<sender>имя3</sender>
		<date>дата3</date> 
	</message>
</messages>';
?>